import { Node } from "../Node.js";

/**
 * Utility class providing cycle-safe object cloning for raw data structures and state payloads across Preempt.
 *
 * @useCase Used during Phase 0 (`InstantiationWorker`) and pipeline operations to clone component binding data, raw JSON objects, and state snapshots without infinite loops.
 * @processFlow Invoked when copying raw node data structures, component values, or pipeline state snapshots.
 * @note **Important Usage Restriction**: `CloneUtils` should NOT be used directly to duplicate live class objects (e.g. `Node`, `Component`, `Handler`, `Placement`, `StyleNode`, `Props`, `Css`). Live class objects must be duplicated via their dedicated `.clone()` instance methods to ensure proper tree linkages, parent references, and render pipeline event emissions.
 */
export class CloneUtils {
  private static readonly CLONE_IGNORE_KEYS = new Set([
    '_lastValidState', 'element', 'node',
    '_instantiatedNodes', '_referencingNodes', 'parent', 'nativeChildren', 'originalParent'
  ]);

  /**
   * Safely deep clones a raw value or data structure using cycle detection (`WeakSet`) and property filtering.
   * Delegates to `val.clone()` if a `.clone()` method exists on the target.
   *
   * @param val Target object, array, or data structure to clone.
   * @param shallowKeys Keys that should be copied by reference rather than deep cloned.
   * @param ignoreKeys Keys that should be excluded/ignored during cloning.
   * @returns Deep cloned copy of the value, or original value on cycle detection fallback.
   * @useCase Deep cloning component values, JSON schemas, and raw state payloads safely.
   * @processFlow Phase 0 Instantiation & Component assembly.
   */
  /**
   * Specifically clones live domain class objects using their class-specific .clone() signatures.
   *
   * @param val Target domain object or array to clone.
   * @param newParent Target parent Node instance if applicable.
   * @param phase Pipeline execution phase ID.
   * @param ignoreProps Property names to ignore.
   * @param shallowProps Property names to copy by reference.
   * @returns Deep cloned copy of domain object.
   */
  public static cloneDomainObject(
    val: any,
    ignoreProps: string[] = [],
    shallowProps: string[] = [],
    newParent?: Node | null,
    phase: number = 99,
    isComponent: boolean = false,
    actor: string = 'Snapshot'
  ): any {
    if (val === null || val === undefined || typeof val !== 'object') {
      return val;
    }

    if (Array.isArray(val)) {
      return val.map(item => CloneUtils.cloneDomainObject(item, ignoreProps, shallowProps, newParent, phase, isComponent, actor));
    }

    const className = val.constructor?.name;

    // Node: clone(ignoreProps, shallowCopyProps, newParent, phase, isComponent, actor)
    if (className === 'Node' || (typeof val.clone === 'function' && '_layers' in val)) {
      return val.clone(ignoreProps, shallowProps, newParent || null, phase, isComponent, actor);
    }

    // NodeLayer: clone(ignoreProps, shallowCopyProps, newParent, phase, isComponent, actor)
    if (className === 'NodeLayer' || (typeof val.clone === 'function' && 'targetProperty' in val && 'sourceName' in val)) {
      return val.clone(ignoreProps, shallowProps, newParent || null, phase, isComponent, actor);
    }

    // Component: clone(ignoreProps, newParent, phase, actor)
    if (className === 'Component' || (typeof val.clone === 'function' && 'reference' in val && 'target' in val)) {
      return val.clone(ignoreProps, newParent || undefined, phase);
    }

    // Handler: clone(newParent, phase, actor)
    if (className === 'Handler' || (typeof val.clone === 'function' && 'event' in val && 'body' in val)) {
      return val.clone(newParent || undefined, phase);
    }

    // Placement: clone(ignoreProps, newParent, phase, actor)
    if (className === 'Placement' || (typeof val.clone === 'function' && 'placementName' in val)) {
      return val.clone(ignoreProps, newParent || undefined, phase);
    }

    // StyleNode: clone(parent)
    if (className === 'StyleNode' || (typeof val.clone === 'function' && 'selector' in val)) {
      return val.clone(newParent || null);
    }

    // Props: clone(ignoreProps, node, actor)
    if (className === 'Props' || (typeof val.clone === 'function' && 'merge' in val && 'isIdAutoGenerated' in val)) {
      return val.clone(ignoreProps, newParent || undefined);
    }

    // Css: clone(ignoreProps, node, actor)
    if (className === 'Css' || (typeof val.clone === 'function' && 'classes' in val && 'style' in val)) {
      return val.clone(ignoreProps, newParent || undefined);
    }

    // Payload: clone(ignoreProps, actor)
    if (className === 'Payload' || (typeof val.clone === 'function' && 'content' in val)) {
      return val.clone(ignoreProps);
    }

    // Template: clone(ignoreProps, actor)
    if (className === 'Template' || (typeof val.clone === 'function' && 'root' in val)) {
      return val.clone(ignoreProps);
    }

    // WorkerMessage: clone(actor)
    if (className === 'WorkerMessage' || (typeof val.clone === 'function' && 'instructions' in val && 'changelog' in val)) {
      return val.clone('Clone');
    }

    // Fallback for cycle-safe raw JSON data structures
    return CloneUtils.deepClone(val, shallowProps, ignoreProps);
  }

  /**
   * Safely deep clones a raw value or data structure using cycle detection (`WeakSet`) and property filtering.
   *
   * @param val Target object, array, or data structure to clone.
   * @param shallowKeys Keys that should be copied by reference rather than deep cloned.
   * @param ignoreKeys Keys that should be excluded/ignored during cloning.
   * @returns Deep cloned copy of the value, or original value on cycle detection fallback.
   * @useCase Deep cloning component values, JSON schemas, and raw state payloads safely.
   * @processFlow Phase 0 Instantiation & Component assembly.
   */
  public static deepClone(val: any, shallowKeys: string[] = [], ignoreKeys: Iterable<string> = CloneUtils.CLONE_IGNORE_KEYS): any {
    if (val === undefined) return undefined;

    if (val !== null && typeof val === 'object' && typeof val.clone === 'function') {
      return CloneUtils.cloneDomainObject(val, Array.from(ignoreKeys), shallowKeys, null, 99);
    }

    const seen = new WeakSet();
    const ignoreSet = ignoreKeys instanceof Set ? ignoreKeys : new Set(ignoreKeys);
    const replacer = (k: string, v: any) => {
      if (shallowKeys.includes(k)) return undefined;

      if (ignoreSet.has(k)) return undefined;

      if (typeof v === "object" && v !== null) {
        if (seen.has(v)) return undefined; // Prevent cycle
        seen.add(v);
      }
      return v;
    };
    try {
      const cloned = JSON.parse(JSON.stringify(val, replacer));
      if (val !== null && typeof val === 'object' && cloned !== null && typeof cloned === 'object') {
        for (const key of shallowKeys) {
          if (key in val) cloned[key] = val[key];
        }

      }
      return cloned;
    } catch (e) {
      console.warn("Cycle detected during deepClone, falling back", e);
      return val;
    }
  }
}

