import { describe, it, expect } from 'vitest';
import { Node } from '../../../src/core/Node.js';

describe('Node Cloning ID Synchronization', () => {
  it('regenerates a fresh unique ID for clones when original node has an auto-generated ID', () => {
    const original = new Node({ type: 'div', content: 'Original' }, null, 0);

    expect(original.props.isIdAutoGenerated).toBe(true);
    expect(original.props.id).toBeDefined();
    expect(original.css?.id).toBe(original.props.id);

    const clone = original.clone([], [], null, 0);

    expect(clone).not.toBe(original);
    expect(clone.props.isIdAutoGenerated).toBe(true);
    expect(clone.props.id).toBeDefined();
    expect(clone.css?.id).toBe(clone.props.id);

    // Critical assertion: clone ID MUST be fresh and not equal to original ID!
    expect(clone.props.id).not.toBe(original.props.id);
    expect(clone.css?.id).not.toBe(original.css?.id);
  });

  it('preserves custom IDs and keeps css.id synchronized with props.id when provided', () => {
    const original = new Node({ type: 'section', props: { id: 'custom-section-id' } }, null, 0);

    expect(original.props.isIdAutoGenerated).toBe(false);
    expect(original.props.id).toBe('custom-section-id');
    expect(original.css?.id).toBe('custom-section-id');

    const clone = original.clone([], [], null, 0);

    expect(clone.props.id).toBe('custom-section-id');
    expect(clone.css?.id).toBe('custom-section-id');
  });

  it('strips auto-generated preempt-node- IDs in exportToJson', () => {
    const node = new Node({ type: 'p', content: 'Text' }, null, 0);
    const json = node.exportToJson();

    expect(json.props?.id).toBeUndefined();
    expect(json.css?.id).toBeUndefined();
  });
});
