import type { LayerMode } from "../types/NodeSchema.js";

/**
 * Encapsulates a single-property reversible change layer on a Node.
 *
 * @useCase Foundation of the idempotent layer stack on Node instances.
 * @processFlow Generated by placements, type components, slot components, phase handlers, and receiveNextState calls.
 */
export class NodeLayer {
  public id: string;
  public targetProperty: string;
  public sourceName: string;
  public mode: LayerMode;
  public value: any;
  public phase?: number | undefined;
  public timestamp: number;

  /**
   * Constructs a new NodeLayer instance.
   *
   * @param targetProperty Single target property string (e.g. 'type', 'children', 'props.href', 'css.color').
   * @param sourceName Source identifier string (e.g. placement name, component reference, receiveNextState name).
   * @param mode Layer operating mode ('replace', 'append', or 'replaceAll').
   * @param value Property modification value.
   * @param phase Pipeline phase ID associated with layer creation.
   */
  constructor(
    targetProperty: string,
    sourceName: string,
    mode: LayerMode,
    value: any,
    phase?: number
  ) {
    this.id = `layer-${Math.random().toString(36).substring(2, 9)}-${Date.now()}`;
    this.targetProperty = targetProperty;
    this.sourceName = sourceName;
    this.mode = mode;
    this.value = value;
    this.phase = phase;
    this.timestamp = Date.now();
  }

  /**
   * Deep duplicates this layer instance.
   *
   * @returns Cloned NodeLayer object.
   */
  public clone(): NodeLayer {
    let valCopy = this.value;
    if (Array.isArray(this.value)) {
      valCopy = [...this.value];
    } else if (this.value && typeof this.value === 'object' && typeof this.value.clone === 'function') {
      valCopy = this.value.clone();
    } else if (this.value && typeof this.value === 'object') {
      valCopy = { ...this.value };
    }

    const cloned = new NodeLayer(this.targetProperty, this.sourceName, this.mode, valCopy, this.phase);
    cloned.id = this.id;
    cloned.timestamp = this.timestamp;
    return cloned;
  }

  /**
   * Releases resources associated with this layer, deleting any contained Nodes, StyleNodes, Components, or Handlers.
   */
  public delete(): void {
    if (Array.isArray(this.value)) {
      for (const item of this.value) {
        if (item && typeof item.delete === 'function') {
          item.delete();
        }
      }
    } else if (this.value && typeof this.value === 'object' && typeof this.value.delete === 'function') {
      this.value.delete();
    }
    this.value = null;
  }
}
