import type { Node } from "./Node.js";
import { CloneUtils } from "./utils/CloneUtils.js";
import { Supervisor } from "./Supervisor.js";

export class Props {
  public parent?: Node;
  private _isIdAutoGenerated: boolean = false;
  [key: string]: any;

  constructor(data: Record<string, any> = {}, parent?: Node, isIdAutoGenerated: boolean = false) {
    Object.defineProperty(this, 'parent', {
      value: parent,
      enumerable: false,
      writable: true,
      configurable: true
    });
    Object.defineProperty(this, '_isIdAutoGenerated', {
      value: isIdAutoGenerated,
      enumerable: false,
      writable: true,
      configurable: true
    });
    for (const [key, value] of Object.entries(data)) {
      if (key !== 'parent' && key !== '_isIdAutoGenerated') {
        this[key] = CloneUtils.deepClone(value);
      }
    }
  }

  public get isIdAutoGenerated(): boolean {
    return this._isIdAutoGenerated;
  }

  public set isIdAutoGenerated(val: boolean) {
    this._isIdAutoGenerated = val;
  }

  public merge(otherProps: Props | Record<string, any>): number | undefined {
    if (Supervisor.isPropertyLocked('props')) {
      console.error(`[Props] Lock violation: Property 'props' is currently locked for node ${this.parent?.css?.id || 'unknown'}`);
      return undefined;
    }
    const entries = otherProps instanceof Props ? Object.entries(otherProps) : Object.entries(otherProps);
    for (const [key, value] of entries) {
      if (key === 'parent' || key === '_isIdAutoGenerated') continue;
      if (key === 'id' && this._isIdAutoGenerated && otherProps instanceof Props && (otherProps as any)._isIdAutoGenerated) {
        continue;
      }
      if (this[key] && typeof this[key] === 'object' && !Array.isArray(this[key]) && value && typeof value === 'object' && !Array.isArray(value)) {
        this[key] = { ...this[key], ...CloneUtils.deepClone(value) };
      } else {
        this[key] = CloneUtils.deepClone(value);
      }
    }
    return 5;
  }

  public clone(ignoreProps: string[] = [], newParent?: Node): Props {
    const parentNode = newParent || this.parent;
    const propsObj: Record<string, any> = {};
    for (const [key, value] of Object.entries(this)) {
      if (key === 'parent' || key === '_isIdAutoGenerated' || ignoreProps.includes(key)) continue;
      if (key === 'id' && this._isIdAutoGenerated) continue;
      propsObj[key] = CloneUtils.deepClone(value);
    }
    return new Props(propsObj, parentNode, false);
  }
}
