import type { Node } from "./Node.js";
import { CloneUtils } from "./utils/CloneUtils.js";
import { Supervisor } from "./Supervisor.js";

/**
 * Encapsulates dynamic DOM attributes and property key-value dictionaries for a Node.
 *
 * @useCase Attached to `node.props` to store attributes like `id`, `src`, `href`, `placeholder`, `value`, `disabled`, etc.
 * @processFlow Processed in Phase 5 (`ValidationWorker`) and Phase 6 (`ClientElementCreationWorker`/`SSRElementCreationWorker`).
 */
export class Props {
  public parent?: Node;
  private _isIdAutoGenerated: boolean = false;
  [key: string]: any;

  /**
   * Constructs a new Props instance.
   *
   * @param data Initial properties dictionary.
   * @param parent Host Node instance.
   * @param isIdAutoGenerated Boolean indicating if node ID was auto-generated.
   */
  constructor(data: Record<string, any> = {}, parent?: Node, isIdAutoGenerated: boolean = false) {
    Object.defineProperty(this, 'parent', {
      value: parent,
      enumerable: false,
      writable: true,
      configurable: true
    });
    Object.defineProperty(this, '_isIdAutoGenerated', {
      value: isIdAutoGenerated,
      enumerable: false,
      writable: true,
      configurable: true
    });
    for (const [key, value] of Object.entries(data)) {
      if (key !== 'parent' && key !== '_isIdAutoGenerated') {
        this[key] = CloneUtils.deepClone(value);
      }
    }
  }

  /** Gets whether the node ID was auto-generated. */
  public get isIdAutoGenerated(): boolean {
    return this._isIdAutoGenerated;
  }

  /** Sets whether the node ID was auto-generated. */
  public set isIdAutoGenerated(val: boolean) {
    this._isIdAutoGenerated = val;
  }

  /**
   * Merges incoming properties into this instance.
   *
   * @param otherProps Incoming Props object or raw properties dictionary.
   * @returns Target phase ID 5 or undefined on property lock violation.
   */
  public merge(otherProps: Props | Record<string, any>): number | undefined {
    if (Supervisor.isPropertyLocked('props')) {
      console.error(`[Props] Lock violation: Property 'props' is currently locked for node ${this.parent?.css?.id || 'unknown'}`);
      return undefined;
    }
    const entries = otherProps instanceof Props ? Object.entries(otherProps) : Object.entries(otherProps);
    for (const [key, value] of entries) {
      if (key === 'parent' || key === '_isIdAutoGenerated') continue;
      if (key === 'id' && this._isIdAutoGenerated && otherProps instanceof Props && (otherProps as any)._isIdAutoGenerated) {
        continue;
      }
      if (this[key] && typeof this[key] === 'object' && !Array.isArray(this[key]) && value && typeof value === 'object' && !Array.isArray(value)) {
        this[key] = { ...this[key], ...CloneUtils.deepClone(value) };
      } else {
        this[key] = CloneUtils.deepClone(value);
      }
    }
    return 5;
  }

  /**
   * Deep clones this Props object.
   *
   * @param ignoreProps Array of property keys to exclude.
   * @param newParent Host Node instance.
   * @returns Cloned Props instance.
   */
  public clone(ignoreProps: string[] = [], newParent?: Node): Props {
    const parentNode = newParent || this.parent;
    const propsObj: Record<string, any> = {};
    for (const [key, value] of Object.entries(this)) {
      if (key === 'parent' || key === '_isIdAutoGenerated' || ignoreProps.includes(key)) continue;
      if (key === 'id' && this._isIdAutoGenerated) continue;
      propsObj[key] = CloneUtils.deepClone(value);
    }
    return new Props(propsObj, parentNode, false);
  }
}

